project_name: spiffe-vault

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: binary
    dir: cmd/spiffe-vault
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - 8
    ldflags:
      - "{{ .Env.LDFLAGS }}"

archives:
  - id: archive
    format: tar.gz
    replacements:
      darwin: macOS
    files:
      - LICENSE*
      - README*
    format_overrides:
      - goos: windows
        format: zip

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "philipssoftware/{{ .ProjectName }}:{{ .Tag }}"
      - "philipssoftware/{{ .ProjectName }}:{{ .Env.GIT_HASH }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:{{ .Tag }}"
      - "ghcr.io/philips-labs/{{ .ProjectName }}:{{ .Env.GIT_HASH }}"
    build_flag_templates:
      - "--pull"
      - "--label=com.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.description={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.licenses=MIT"
    extra_files:
      - "Makefile"
      - "go.mod"
      - "go.sum"
      - "cmd"
      - "pkg"
checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

release:
  prerelease: auto
