name: Go CI

on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-26.04

    name: Continuous Integration

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Get dependencies
        run: go mod download

      - name: Lint
        run: |
          result=$(make lint)
          echo "$result"
          if grep -q 'diff -u' <<< "$result"; then
            exit 1
          fi

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Coverage
        run: make coverage-out

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v7.1.1
        with:
          use_oidc: true
          files: ./coverage.out
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  release:
    name: release
    needs: [build]
    runs-on: ubuntu-26.04

    permissions:
      contents: write
      packages: write

    outputs:
      container_digest: ${{ steps.container_info.outputs.container_digest }}
      container_tags: ${{ steps.container_info.outputs.container_tags }}
      container_repos: ${{ steps.container_info.outputs.container_repos }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.2
        with:
          cosign-release: "v2.6.0"

      - name: Login to container registries
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          printf '%s' "$GITHUB_TOKEN" | docker login \
            -u "$GITHUB_ACTOR" --password-stdin ghcr.io
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}

      - name: Set release variables
        id: release-vars
        run: |
          make release-vars > /tmp/spiffe-vault-release-vars.env
          source /tmp/spiffe-vault-release-vars.env
          if [[ -n "$LDFLAGS" ]]; then
            echo "ldflags=$LDFLAGS" >> "$GITHUB_OUTPUT"
          fi
          if [[ -n "$GIT_HASH" ]]; then
            echo "git_hash=$GIT_HASH" >> "$GITHUB_OUTPUT"
          fi
          rm -f /tmp/spiffe-vault-release-vars.env

      - name: Install signing key
        run: |
          printf '%s\n' "$COSIGN_PRIVATE_KEY" > cosign.key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}

      - name: Buildx builder
        run: make container-builder

      - name: Release
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: >-
            release --clean
            ${{ (!startsWith(github.ref, 'refs/tags/') && '--snapshot') || '' }}
        env:
          LDFLAGS: ${{ steps.release-vars.outputs.ldflags }}
          GIT_HASH: ${{ steps.release-vars.outputs.git_hash }}
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}

      - name: Get container info
        id: container_info
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
        run: |
          CONTAINER_DIGEST="$(make container-digest \
            "GITHUB_REF=$GITHUB_REF_NAME")"
          CONTAINER_TAGS="$(make container-tags \
            "CONTAINER_DIGEST=$CONTAINER_DIGEST" | paste -s -d ',' -)"
          CONTAINER_REPOS="$(make container-repos \
            "CONTAINER_DIGEST=$CONTAINER_DIGEST" | jq --raw-input . \
            | jq --slurp -c)"
          {
            printf 'container_digest=%s\n' "$CONTAINER_DIGEST"
            printf 'container_tags=%s\n' "$CONTAINER_TAGS"
            printf 'container_repos=%s\n' "$CONTAINER_REPOS"
          } >> "$GITHUB_OUTPUT"

      - name: Logout from container registries
        if: ${{ always() }}
        run: |
          docker logout ghcr.io

      - name: Cleanup signing keys
        if: ${{ always() }}
        run: rm -f cosign.key

  provenance:
    name: Generate provenance
    runs-on: ubuntu-26.04
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      actions: read
      contents: write
      id-token: write

    steps:
      - name: Generate provenance for release
        uses: philips-labs/slsa-provenance-action@v0.9.0
        with:
          command: generate
          subcommand: github-release
          arguments: >-
            --artifact-path release-assets --output-path provenance.att
            --tag-name ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.2
        with:
          cosign-release: "v2.6.0"

      - name: Sign provenance
        run: |
          printf '%s\n' "$COSIGN_PRIVATE_KEY" > cosign.key
          cosign sign-blob --key cosign.key \
            --output-signature "${SIGNATURE}" provenance.att
          cat "${SIGNATURE}"

          curl_args=(-s -H "Authorization: token ${GITHUB_TOKEN}")
          curl_args+=(-H "Accept: application/vnd.github.v3+json")
          releases_url="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/releases?per_page=10"
          releases="$(curl "${curl_args[@]}" "$releases_url")"
          release_id="$(jq --arg tag "$GITHUB_REF_NAME" \
            'map(select(.name == $tag)) | .[0].id' <<< "$releases")"

          echo "Upload ${SIGNATURE} to release with id ${release_id}…"
          curl_args+=(-H "Content-Type: $(file -b --mime-type "${SIGNATURE}")")
          curl "${curl_args[@]}" \
            --data-binary @"${SIGNATURE}" \
            "https://uploads.github.com/repos/${GITHUB_REPOSITORY}/releases/${release_id}/assets?name=${SIGNATURE}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          SIGNATURE: provenance.att.sig

  container-provenance:
    name: container-provenance
    needs: [release]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-26.04

    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write

    strategy:
      matrix:
        repo: ${{ fromJSON(needs.release.outputs.container_repos) }}

    steps:
      - name: Install cosign
        uses: sigstore/cosign-installer@v4.1.2
        with:
          cosign-release: "v2.6.0"

      - name: Generate provenance for ${{ matrix.repo }}
        uses: philips-labs/slsa-provenance-action@v0.9.0
        with:
          command: generate
          subcommand: container
          arguments: >-
            --repository ${{ matrix.repo }} --output-path provenance.att
            --digest ${{ needs.release.outputs.container_digest }}
            --tags ${{ needs.release.outputs.container_tags }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Get slsa-provenance predicate
        run: |
          cat provenance.att | jq .predicate > provenance-predicate.att

      - name: Login to Container registries
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          printf '%s' "$GITHUB_TOKEN" | docker login \
            -u "$GITHUB_ACTOR" --password-stdin ghcr.io

      - name: Attach provenance to image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
          CONTAINER_REPOSITORY: ${{ matrix.repo }}
          CONTAINER_DIGEST: ${{ needs.release.outputs.container_digest }}
        run: |
          printf '%s\n' "$COSIGN_PRIVATE_KEY" > cosign.key
          cosign attest --predicate provenance-predicate.att \
            --type slsaprovenance --key cosign.key \
            "$CONTAINER_REPOSITORY@$CONTAINER_DIGEST"

      - name: Verify attestation
        env:
          COSIGN_PUBLIC_KEY: ${{ secrets.COSIGN_PUBLIC_KEY }}
          CONTAINER_REPOSITORY: ${{ matrix.repo }}
          CONTAINER_DIGEST: ${{ needs.release.outputs.container_digest }}
        run: |
          printf '%s\n' "$COSIGN_PUBLIC_KEY" > cosign.pub
          cosign verify-attestation --key cosign.pub \
            "$CONTAINER_REPOSITORY@$CONTAINER_DIGEST"

      - name: Logout from Container registries
        if: ${{ always() }}
        run: |
          docker logout ghcr.io
          rm -f cosign.key
